name: online_automobile_service
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  firebase_auth: ^4.2.9
  google_sign_in: ^6.0.1
  provider: ^6.0.5
  firebase_core: ^2.7.0
  carousel_slider: ^4.2.1
  url_launcher: ^6.1.10
  flutter_phone_direct_caller: ^2.1.1
  fluttertoast: ^8.2.1
  flutter_screenutil: ^5.6.1
  share: ^2.0.4
  path_provider: ^2.0.13
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  image_path: "assets/logo/logo.png" 
  android: true
  ios: true  

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/images/
    - assets/data/
    - assets/
